volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6.2.6
        container_name: langgraph-redis
        hostname: langgraph-redis
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:14.2
        hostname: langgraph-postgres
        container_name: langgraph-postgres
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: my-image:1.0
        container_name: langgraph-api
        hostname: langgraph-api
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        env_file:
            - .env
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            LANGSMITH_API_KEY: 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
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable